In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GridSearchCV, train_test_split

In [3]:
df = pd.read_csv(r"/content/advertising.csv")

In [11]:
df.head(3)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [6]:
#missing values
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [7]:
# duplicate values
df.duplicated().sum()

np.int64(0)

In [19]:
X = df.drop("Sales", axis=1)
y = df["Sales"]

In [20]:
#train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
#standard Scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
#model training
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [23]:
#prediction
y_pred = lr.predict(X_test)

In [24]:
#model evaluation
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9059011844150825

In [26]:
#pipeline
from sklearn.pipeline import Pipeline
pipeline = Pipeline([('scaler', StandardScaler()), ('lr', LinearRegression())])

In [31]:
#setting parameters
param_grid = {'lr__fit_intercept': [True, False],
              'lr__positive': [True, False]
              }

In [32]:
#defining tuning grid
grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1

)

In [33]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('lr', LinearRegression())]),
             n_jobs=-1,
             param_grid={'lr__fit_intercept': [True, False],
                         'lr__positive': [True, False]},
             scoring='r2')

In [35]:
print('Best Params:', grid_search.best_params_)

Best Params: {'lr__fit_intercept': True, 'lr__positive': False}